environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run prebuild

test_script:
  - node --version
  - npm --version
  - dir /w
  - dir /w prebuilds

artifacts:
  - path: 'prebuilds\*.tar.gz'
    name: kerberos

deploy:
  - provider: S3
    access_key_id: AKIAJBRBFVFYSPAEPT5Q
    secret_access_key:
      secure: mnfzcUrMCjMzLYjo8Gy+b+ZJbqaf0Mr0guJhdJYByXtY/p3NEYlzXEfLPWZTbwyi
    region: us-east-1
    bucket: studio-native-dependencies
    artifact: kerberos
    max_error_retry: 1

