environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run prebuild

test_script:
  - node --version
  - npm --version
  - dir /w
  - dir /w prebuilds

artifacts:
  - path: 'prebuilds\*.tar.gz'
    name: kerberos

deploy:
  - provider: S3
    access_key_id:
      secure: QNtu9t7wpNL/lZMFTS0R9epuavlPmyhfvGfA59torF4=
    secret_access_key:
      secure: BDVHjsolbFf8c3zDxSKnF+B6ZUzXcEzj2VDu6Mxiey9dI/kTuT8qiRViEUimktZ6
    region: us-east-1
    bucket: studio-native-dependencies
    artifact: kerberos
    max_error_retry: 1

